# -*- coding: utf-8 -*-
"""Generate build.bat with correct encoding"""
bat = (
    "@echo off\n"
    "chcp 65001 >nul\n"
    "echo ========================================\n"
    "echo csBaby - Auto Build + OSS Upload\n"
    "echo ========================================\n"
    "echo.\n"
    "\n"
    "set JAVA_HOME=C:\\Users\\13880\\.jdks\\openjdk-26\n"
    "set ANDROID_HOME=D:\\Android\\SDK\n"
    "set ANDROID_SDK_ROOT=D:\\Android\\SDK\n"
    "set PATH=%JAVA_HOME%\\bin;%PATH%\n"
    "\n"
    "echo [1/3] Incrementing version...\n"
    "powershell -NoProfile -File \"D:\\workspace\\workbuddy\\csBaby\\increment_version.ps1\"\n"
    "if errorlevel 1 (\n"
    "    echo [ERROR] Version increment failed\n"
    "    pause\n"
    "    exit /b 1\n"
    ")\n"
    "\n"
    "echo.\n"
    "echo [2/3] Building APK...\n"
    "cd /d D:\\workspace\\workbuddy\\csBaby\n"
    "call gradlew.bat assembleDebug --no-daemon\n"
    "if errorlevel 1 (\n"
    "    echo.\n"
    "    echo [ERROR] Build failed\n"
    "    pause\n"
    "    exit /b 1\n"
    ")\n"
    "\n"
    "echo.\n"
    "echo [OK] Build succeeded\n"
    "\n"
    "echo.\n"
    "echo [3/3] Uploading to OSS...\n"
    "python \"D:\\workspace\\workbuddy\\csBaby\\upload_oss.py\"\n"
    "if errorlevel 1 (\n"
    "    echo.\n"
    "    echo [ERROR] OSS upload failed\n"
    "    pause\n"
    "    exit /b 1\n"
    ")\n"
    "\n"
    "echo.\n"
    "echo ========================================\n"
    "echo ALL DONE!\n"
    "echo ========================================\n"
    "if exist \"D:\\workspace\\workbuddy\\csBaby\\version-info.json\" (\n"
    "    powershell -NoProfile -Command \"$v = Get-Content 'D:\\workspace\\workbuddy\\csBaby\\version-info.json' -Raw | ConvertFrom-Json; Write-Host ('  v' + $v.version_name + ' (' + $v.version_code + ') ' + [math]::Round($v.file_size/1MB,2) + ' MB'); Write-Host ('  ' + $v.apk_url)\"\n"
    ")\n"
    "echo.\n"
    "pause\n"
)

with open(r'D:\workspace\workbuddy\csBaby\build.bat', 'w', encoding='gbk') as f:
    f.write(bat)
print('Done, length:', len(bat))
